CREATE TABLE USERS (
    ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    LOGIN           VARCHAR2(100) NOT NULL UNIQUE,
    EMAIL           VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD   		VARCHAR2(255) NOT NULL,
    ROLE_ID         RAW(16) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT FK_USERS_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ID)
);